### ISSUE TITLE
Please rerun benchmark numbers, new optimizations have landed

### ISSUE THREAD

**Issue by sethladd** [dartist/sudoku_solver#2]
Hi,

When you have a moment, can you please try the latest Dart SDK (>= r29701) with your benchmarks? We have internal tests here that show significant improvements with your solver.

Also, we tested with PyPy in the mix. You might want to add that to your suite.

If you need help getting >= r29701 please let me know.

Thanks!

**Comment by mythz** [comment]
Hey Seth, I'm ultra busy this week preparing for Oredev but I'll get to this as soon as I'm back.

**Comment by sethladd** [comment]
Understood, not a problem. We think you'll like what you see. :)

Good luck at Oredev!

**Comment by mythz** [comment]
Hey Seth, I unfortunately missed my flight so I was able to run the benchmarks now. 

Dart sees a nice 1.3-1.6x improvement which is nice! I also added PyPy as suggested, and it turned out to be insanely fast - now the top dog!

**Comment by sethladd** [comment]
Sorry to hear you missed your flight.
