### ISSUE TITLE
Please test with Dart 0.8.10.3_r29803

### ISSUE THREAD

**Issue by sethladd** [dartist/sudoku_solver#3]
Thanks for updating! Looks like you caught us right before we released 0.8.10.3_r29803 which I'm told has some nice perf improvements inspired by these benchmarks.

No rush, but when you have time, we think the perf is even better with the latest.

**Comment by mythz** [comment]
Ahh apologies thought I did, I just tried updating through the Dart editor and it said it was `Unable to get latest revision`, so I ended up re-downloading from dartlang.org - Updated results to use 0.8.10.3_r29803 (x64), results were noticeably better again, just besting PyPy for top95 grids and only 1.26x - 1.55x slower for grid1/grid2. 

_Note: DartEditor still says 'Unable to get latest revision' when checking for updates_

**Comment by sethladd** [comment]
Thanks for getting the latest. yes, you too found the bug with update. :) Our engineer is looking at it now.

Glad to see the numbers got even better :)
